version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  push-to-branch:
    steps:
      - deploy:
          name: copy master to master dir
          working_directory: ~/
          command: |
            git clone --depth 1 https://${ACCESS_TOKEN}@github.com/rajeevAgilehub/circieci-build-trigger.git masterdir
            rm -rf masterdir/.git
      - deploy:
          name: Dump files to madf dir from master 
          working_directory: ~/
          command: |
            git clone --depth 1 https://${ACCESS_TOKEN}@github.com/rajeevAgilehub/circieci-build-trigger.git -b madf madfdir
            rm -rf madfdir/*
            cd madfdir
            ls -la
            git config credential.helper 'cache --timeout=120'
            git config --global user.email "rajeev.sharma@theagilehub.net"
            git config --global user.name "rajeevAgilehub"
            git config --global github.user "rajeevAgilehub"
            git config --global github.token ${ACCESS_TOKEN}
            git add .
            git commit -m "all files removed except .git"
            cd ../
            cp -r masterdir/* madfdir/
            cd madfdir
            pwd && ls
            git add .
            git commit -m "updated with master"
            # Push quietly to prevent showing the token in log
            git push origin madf          
workflows:
    # build-and-test:
    #   jobs:
    #     - build-and-test
    push-to-branch:
      jobs:
        - push-to-branch